Update failure report when setup_sm.sh not available and when lock file present

diff --git a/operations/functions-storagemanager b/operations/functions-storagemanager
--- a/operations/functions-storagemanager
+++ b/operations/functions-storagemanager
@@ -1,8 +1,8 @@
 # -*-Shell-script-*-
 #
-# functions-storagemanager        This file contains functions to be used
-#                                by all storage manager shell scripts in
-#                                the /etc/init.d directory.
+# functions-storagemanager      This file contains functions to be used
+#                               by all storage manager shell scripts in
+#                               the /etc/init.d directory.
 
 # Source function library.
 if [ -f /etc/init.d/functions ]; then
@@ -19,19 +19,21 @@ if [ ! -x $sets ]; then
     sets=/opt/smops/setup_sm.sh
 fi
 if [ ! -x $sets ]; then
-    failure $"$prog: No suitable setup_sm.sh script found. Aborting."
+    echo "$prog: No suitable setup_sm.sh script found. Aborting."
+    return 1
 fi
 
 storagemanager_start () {
+    MESSAGE="Starting $prog:"
+    echo -n "$MESSAGE "
     if [ -f /var/lock/subsys/$prog ]; then
-        failure $"$prog is already running"
-        return 1
+        echo -n 'already running! '; failure; echo
+        return 2
     fi
-    if action $"Starting $prog:" $sets "start$1"; then
-        touch /var/lock/subsys/$prog
-        return 0
-    fi
-    return 1
+    action "Starting $prog:" $sets "start$1"
+    RETVAL=$?
+    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
+    return $RETVAL
 }
 
 storagemanager_stop () {
